import { ConnectButton } from '@rainbow-me/rainbowkit';
import 'bulmaswatch/sandstone/bulmaswatch.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SwapToken from '../components/SwapToken';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Token Swap App</title>
        <meta
          name='description'
          content='Generated by @rainbow-me/create-rainbowkit'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={styles.header}>
        <ConnectButton />
      </header>
      <main className={styles.main}>
        <SwapToken />
      </main>
    </div>
  );
};

export default Home;
