import { ConnectButton } from '@rainbow-me/rainbowkit';
import 'bulmaswatch/slate/bulmaswatch.min.css';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SwapToken from '../components/SwapToken';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name='description'
          content='Generated by @rainbow-me/create-rainbowkit'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={styles.header}>
        <ConnectButton />
      </header>
      <main className={styles.main}>
        <SwapToken />
      </main>

      <footer className={styles.footer}>
        <a href='https://rainbow.me' target='_blank' rel='noopener noreferrer'>
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
